config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "guitars#index"

  resources :guitars, except: :index do
    resources :orders, only: :create
  end

  resources :orders, only: %i[show destroy]

  get '/my_listings', to: 'guitars#my_guitars', as: :my_guitars
  get '/my_listings/order_history', to: 'orders#my_sales', as: :my_sales

  get '/my_rentals', to: 'orders#my_purchases', as: :my_purchases
end

app/models/guitar.rb
class Guitar < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many_attached :photos
  validates_length_of :photos, minimum: 2, maximum: 5, too_short: "minimum is %{count}", too_long: "maximum is %{count}"

  validates :name, :brand, :model, :price_per_day, :rental_city, :photos, presence: true
  validates :right_handed, presence: { message: "Required" }
  validates :price_per_day, numericality: { only_integer: true }
  validates :year, numericality: { allow_nil: true, only_integer: true, greater_than_or_equal_to: 1930, less_than_or_equal_to: Date.current.year }

  pg_search_scope :search_brand_and_city,
    against: [ :brand, :name, :model, :year, :right_handed ],
    using: {
      tsearch: { prefix: true }
    }

  pg_search_scope :search_by_city, against: :rental_city

  def available?
    current_rental = Order.where(guitar: self).where('start_date <= ? AND end_date >= ?', Date.today, Date.today)
    current_rental.empty?
  end

  def next_availability
    current_rental = Order.where(guitar: self).where('start_date <= ? AND end_date >= ?', Date.today, Date.today)
    available = false
    until available
      next_date = current_rental.first.end_date + 1
      current_rental = Order.where(guitar: self).where('start_date = ? OR start_date + 1 = ?', next_date, next_date)
      available = true if current_rental.empty?
    end
    next_date
  end

  def price_per_day=(value)
    # Remove any non-digit characters from the value
    sanitized_value = value.to_s.gsub(",", ".").gsub(/[^0-9.]/,'')

    # Convert the decimal value to cents and store as an integer
    self[:price_per_day] = (sanitized_value.to_f * 100).to_i
  end

  def unavailable_dates
    orders.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  def can_be_deleted?
    orders.all? { |order| order.status == "Concluded" }
  end
end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
  before_action :set_guitar, only: %i[destroy show edit update]
  skip_before_action :authenticate_user!, only: %i[index show]

  after_action :skip_authorization, only: %i[my_guitars]
  after_action :verify_policy_scoped, only: %i[my_guitars], unless: :skip_pundit?

  def index
    rented_guitars = Order.where('start_date <= ? AND end_date >= ?', Date.today, Date.today).map(&:guitar)
    rented_for_a_while = rented_guitars.reject { |guitar| guitar.next_availability <= Date.today + 15 }
    @guitars = policy_scope(Guitar)
    @guitars = @guitars.search_brand_and_city(params[:query]) if params[:query].present?
    @guitars = @guitars.search_by_city(params[:rental_city]) if params[:rental_city].present?
    if params[:start_date].present? && params[:end_date].present?
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])
      @guitars = @guitars.select do |guitar|
        (start_date..end_date).all? do |date|
          current_rental = Order.where(guitar:).where('start_date <= ? AND end_date >= ?', date, date)
          current_rental.empty?
        end
      end
    else
      @guitars = @guitars.where.not(id: rented_for_a_while.pluck(:id)).where.not(user: current_user)
    end
    @guitars = Guitar.where(id: @guitars.map(&:id)).where.not(user: current_user)
    @guitars.order!(id: :desc)
    @guitars
  end

  def my_guitars
    @guitars = policy_scope(Guitar).where(user: current_user)
    @guitars.order!(id: :desc)
  end

  def show
    authorize @guitar
    @order = Order.new
    authorize @order
  end

  def destroy
    authorize @guitar
    if @guitar.can_be_deleted?
      @guitar.destroy
      redirect_to my_guitars_path, notice: "Guitar was successfully destroyed."
    else
      redirect_to guitars_path, notice: "Cannot delete rented guitar."
    end
  end

  def edit
    authorize @guitar
  end

  def update
    authorize @guitar
    if @guitar.update(guitar_params)
      redirect_to guitar_path(@guitar)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @guitar = Guitar.new
    authorize @guitar
  end

  def create
    @guitar = Guitar.new(guitar_params)
    authorize @guitar
    @guitar.user = current_user
    if @guitar.save
      redirect_to @guitar
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_guitar
    @guitar = Guitar.find(params[:id])
  end

  def guitar_params
    params.require(:guitar).permit(:name, :brand, :model, :description, :material, :pickup, :right_handed, :year, :country, :price_per_day, :rental_city, photos: [])
  end
end

app/views/guitars/edit.html.erb
<div class="container pt-5 pb-5">

  <div class="card-edit-user">
    <h1 class="font-1-xxl mb-x">Edit Guitar<span class="cor-p1">.</span></h1>
    <%= render "shared/guitar_form", guitar: @guitar %>
    <%= link_to "Back", guitar_path(@guitar), class: 'btn-secondary mt-3' %>
  </div>

</div>

app/views/guitars/index.html.erb
<% if user_signed_in? %>
    <%= render "shared/logged_user_banner", user: current_user %>
<% else %>
    <%= render "shared/new_user_banner"%>
<% end %>

<div class="container mt-5 mb-5">

<h2 id="h2" class="font-1-xxl">Choose yours<span class="cor-p1">.</span></h2>

 <div class="mt-3 mb-3">
    <%= form_with url: root_path, method: :get, class: "form-grid" do %>
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Type Keyword"%>
      <%= select_tag :rental_city, options_for_select(Guitar.pluck(:rental_city).uniq, params[:rental_city]), prompt: "Select a city", class: "form-control" %>
      <%= date_field_tag :start_date, params[:start_date],  class: "form-control", placeholder: "Type date" %>
      <%= date_field_tag :end_date, params[:end_date],  class: "form-control", placeholder: "Type date" %>
      <%= submit_tag "Search", name: "", class: "btn btn-secondary" %>
    <% end %>
 </div>

  <%= render "shared/guitar_cards", guitars: @guitars %>
</div>

app/views/guitars/my_guitars.html.erb
<div class="container mt-5 mb-5">
  <div class="flex-intro">

    <h1 class="font-1-xxl mb-x">My guitars<span class="cor-p1">.</span></h1>
    <%= link_to 'Add Guitar', new_guitar_path, class: 'btn-add mb-5' %>

  </div>

  <div class="my-listing-grid">

    <%= render "shared/guitar_cards", guitars: @guitars %>

    <div class="my-listing-menu">
        <%= link_to 'Rental history', my_sales_path, class: 'btn-secondary' %>
    </div>
  </div>

</div>

app/views/guitars/new.html.erb
<div class="background-new-guitar">
<div class="container py-5">

    <div class="card-edit-user">
      <h1 class="font-1-xxl mb-x">List new Guitar<span class="cor-p1">.</span></h1>
      <%= render "shared/guitar_form", guitar: @guitar %>
    </div>

  </div>
</div>

app/views/guitars/show.html.erb
<% "random text" %>

<div class="container mt-5 mb-5">
  <div class="grid-product">
    <div class="product-media" data-controller="picker">
      <% if @guitar.photos.attached? %>
        <div class="media-gallery">
          <% @guitar.photos[1..].each do |photo|%>
            <%= cl_image_tag photo.key, class:"product-image secondary-image", data: {action:"click->picker#changeImage"} %>
          <% end %>
        </div>
                <div id="bigger-image">

      <%= cl_image_tag @guitar.photos[0].key, class:"product-image primary-image", data: {'picker-target': "pimage"} %>
</div>
      <% else %>
        <div>
          <%= image_tag "guitar.webp", class: "product-image primary-image" %>
        </div>
      <% end %>
    </div>


    <div class="product-info">
      <h1><%= @guitar.name %></h1>
      <p><%= @guitar.description %></p>
      <span class="price"> <%= number_to_currency(@guitar.price_per_day / 100.0, unit: "R$ ", delimiter: "") %></span>
      <% if @guitar.available?%>
        <p class="available">Available</p>
      <% else %>
        <p class="not-available">Available <%= @guitar.next_availability.strftime("%d/%m/%y")%></p>
      <% end %>
      <div>
      <% if user_signed_in? %>
        <% if policy(@guitar).edit? %>
          <%= link_to "Edit", edit_guitar_path(@guitar), class: 'btn-card-4 btn-secondary' %>
        <% else %>
          <div id='guitar-booking-dates' data-controller='flatpickr' data-unavailable='<%=@guitar.unavailable_dates.to_json%>'>
            <%= simple_form_for [@guitar, @order] do |f| %>
              <div class='d-flex gap-3'>
                <%= f.input :start_date, label: 'Rental Date', as: :string, type: :text, input_html: {class: 'datepicker'} %>
                <%= f.input :end_date, label: 'Return Date', as: :string, type: :text, input_html: {class: 'datepicker'} %>
              </div>
              <%= f.submit "Rent Guitar", class: "btn btn-rent" %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <%= link_to "Login to rent", new_user_session_path, class: "btn-card-4 btn-secondary" %>
      <% end %>
      </div>
      <div class="details">
      <h3>Technical Details</h3>
        <div class="details-list">
          <ul>
            <li>Brand<span><%= @guitar.brand %></span></li>
            <li>Model<span><%= @guitar.model %></span></li>
            <li>Material<span><%= @guitar.material %></span></li>
            <li>Pickup<span><%= @guitar.pickup %></span></li>
            <li>Ano<span><%= @guitar.year %></span></li>
            <li>País<span><%= @guitar.country %></span></li>
            <li>Cidade<span><%= @guitar.rental_city %></span></li>
            <li>Handed<span><%= @guitar.right_handed ? 'Right Handed': 'Left Handed' %></span></li>
          </ul>
        </div>
      </div>
        <% if policy(@guitar).destroy? %>
          <%= link_to "Delete", guitar_path(@guitar), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn-delete mt-4' %>
        <% end %>
    </div>
  </div>
</div>

<%# <div class='container'>
  <%= simple_form_for [@guitar, @order] do |f|
    <%= f.input :start_date
    <%= f.input :end_date
    <%= f.submit 'Rent Guitar', class: 'btn btn-primary'
  <% end
</div> %>