config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "guitars#index"

  resources :guitars, except: :index do
    resources :orders, only: :create
  end

  resources :orders, only: %i[show destroy]

  get '/my_listings', to: 'guitars#my_guitars', as: :my_guitars
  get '/my_listings/order_history', to: 'orders#my_sales', as: :my_sales

  get '/my_rentals', to: 'orders#my_purchases', as: :my_purchases
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <footer>
  <div class="footer-background">
    <div class="container">
      <div class="footer-grid">
      <div>
        <p class="cor-2 font-1-s">Rent the best guitars and play your show<span class="cor-p1 font-1-m-b"> .</span></p>
        </div>
        <span class="cor-5 font-1-xs">© GuitarZ Switch - Todos os direitos resevados</span>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_guitar_cards.html.erb
<div class="cards">
  <% guitars.each do |guitar| %>
    <div class="card-product">
      <% if guitar.photos[0] %>
        <%= cl_image_tag(guitar.photos[0].key, class: 'product-image') %>
      <% end %>
      <div class="card-product-infos">
        <div>
        <h3><%= guitar.name %></h3>
        <p><%= guitar.rental_city %></p>
        <% if guitar.available?%>
          <span class="available">Available</span>
        <% else %>
          <span class="not-available">Available <%= guitar.next_availability.strftime("%d/%m/%y")%></span>
        <% end %>
        </div>
      <span class="price"><%= number_to_currency(guitar.price_per_day / 100.0, unit: "R$ ", delimiter: "") %> </span>
      </div>
      <%= link_to "View Details", guitar_path(guitar), class:"btn-rent btn-card-2 btn-card-3" %>
      <% if policy(guitar).edit? %>
        <%= link_to "Edit", edit_guitar_path(guitar), class:"btn-card btn-secondary" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_guitar_form.html.erb
  <%= simple_form_for guitar do |f| %>
    <%= f.input :name, label: 'Title', placeholder: 'ex: Gibson Limited Edition 58 Hot Rod Les Paul 2008 Red' %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }%>
    <%= f.input :brand, placeholder: 'ex: Gibson, Fender, Ibanez...'%>
    <%= f.input :model, placeholder: 'ex: Les Paul, Startocaster, Flying V...' %>
    <%= f.input :year, as: :integer, placeholder: 'Production year'%>
    <%= f.input :country, label: 'Made in' %>
    <%= f.input :description, as: :text %>
    <%= f.input :material, placeholder: 'ex: Mahogany, Walnut, Maple...' %>
    <%= f.input :pickup %>
    <%= f.input :right_handed, legend_tag: false, as: :radio_buttons, collection: ['Right Handed', 'Left Handed'] %>
    <%= f.input :rental_city, as: :select, collection: ['São Paulo', 'Rio de Janeiro'], placeholder: 'The city you are renting in' %>
    <%= f.input :price_per_day, label: "Price per day (R$)", placeholder: 'ex: 45,30', input_html: { step: '0.01' } %>
    <%= f.submit guitar.id.nil? ? 'Create Listing' : 'Edit Listing', class:"btn btn-add" %>
  <% end %>

<script>
  const priceInput = document.getElementById('price-input');

  priceInput.addEventListener('input', function(e) {
    const input = (e.target.value.to_s.gsub(",", ".").gsub(/[^0-9.]/,'')*100).to_i;
    const formattedValue = (input / 100).toFixed(2);
  });
</script>

app/views/shared/_logged_user_banner.html.erb
<div class="banner-logged">
  <div class="container">

    <div class="banner-info-logged">
    <h1 class="font-1-xl cor-12">Welcome back <span class="cor-p1"><%= user.first_name %></span></h1>
    <p class="font-2-m cor-8 mb-3">Rent the best guitars in town and start shredding today</p>

    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag src="logo-text.svg", width: 300 %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Find a Guitar", "/", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "List a Guitar", new_guitar_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Rentals", my_purchases_path, class: "nav-link" %>
          </li>
          <li class="nav-item last">
            <%= link_to "My Listings", my_guitars_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <%= image_tag "user.png", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", "/users/edit", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new_user_banner.html.erb
<div class="banner">
  <div class="container">

    <div class="banner-info">
    <h1 class="font-1-xxl cor-12">Rent a Guitar, Now<span class="cor-p1">.</span></h1>
    <p class="font-2-l cor-8 mb-3">Rent the best guitars in town and start shredding today</p>
    <div class="buttons-home">
    <%= link_to "Find a Guitar", root_path(anchor: "h2"), class:"btn-primary" %>
    <%= link_to "Rent a Guitar", new_guitar_path, class:"btn-secondary" %>
    </div>

    </div>

  </div>
</div>

app/views/shared/_order_cards.html.erb
<div class="rental-list">
  <% orders.each do |order| %>
  <div class="rental-card">
    <h3><%= order.guitar.name%></h3>
    <div class="order-date">
    <p>Status: <%= order.status%></p>
    <p><%= number_to_currency(order.price / 100.0, unit: "R$ ", delimiter: "")%></p>
    </div>
    <% if order.status == "Upcoming" && policy(order).destroy? %>
      <%= link_to "Cancel", order_path(order), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn-delete' %>
    <% end %>
    <%= link_to "Order details", order_path(order), class: 'btn-primary' %>
  </div>
  <% end %>
</div>
<%= link_to 'Back', url_for(:back), class: 'btn-third mtb-x' %>